In [15]:
# 1. Import the numpy package under the name
import numpy as np

In [14]:
# 2. Print the numpy version and the configuration v1
import numpy
print(numpy.version.version)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/alici/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/alici/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/alici/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/alici/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/alici/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/alici/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/alici/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/alici/anaconda3\\Library\\include']
None


In [16]:
# 2. Print the numpy version and the configuration v2
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/alici/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/alici/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/alici/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/alici/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/alici/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/alici/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/alici/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/alici/anaconda3\\Library\\include']
None


In [17]:
# 3. Create a null vector of size 10 
s = np.zeros(10)
print(s)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [18]:
# 4. How to find the memory size of any array
s = np.zeros(10)
print("%d bytes" % (s.size * s.itemsize))

80 bytes


In [19]:
# 5. How to get the DOCUMENTATION of the numpy add function from the command line?

In [21]:
# 6. Create a null vector of size 10 but the fifth value which is 1 
t = np.zeros(10)
t[4]=1
print(t)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [22]:
# 7. Create a vector with values ranging from 10 to 49
u = np.arange(10,50)
print(u)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [23]:
# 8. Reverse a vector (first element becomes last)
u = u[::-1]
print(u)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [24]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8 
m = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [25]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
w = np.nonzero([1,2,0,0,4,0])
print(w)

(array([0, 1, 4], dtype=int64),)
