In [117]:
import numpy as np

e = np.random.random((2,2))
print(e)

[[0.54019963 0.48923204]
 [0.92954977 0.92340502]]


In [118]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [119]:
c = np.full((4,3), 7)
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]


In [120]:
b = np.ones((5,2))
print(b)  

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [121]:
a = np.array([1, 2, 3,])
print(a[0], a[], a[2])

SyntaxError: invalid syntax (<ipython-input-121-adbaab848d3b>, line 2)

In [29]:
 Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a[:])

SyntaxError: invalid syntax (<ipython-input-29-4f46b8ea64b5>, line 1)

In [27]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b= a[:2], [1:3]

SyntaxError: invalid syntax (<ipython-input-27-a4beb4fd6b1d>, line 5)

In [64]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = a[:2, :4]
row_r2 = a[:3, :3]
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [72]:
import numpy as np

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

# Create an array of indices
b = np.array([0, 2, 0, 0])
print(a[np.arange(4), b])

[ 1  6  7 10]


In [74]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([0, 2, 0, 1])
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [78]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a[a >= 3])

[3 4 5 6]


In [83]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]


In [85]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])
print(np.dot(v, w))

219


In [87]:
# importing pandas as pd 
import pandas as pd 
   
# dictionary of lists 
dict = {'name':["Sunil", "pankaj", "sudhir", "Geeku"], 
        'degree': ["MBA", "BCA", "M.Tech", "MBA"], 
        'score':[90, 40, 80, 98]} 
   
df = pd.DataFrame(dict) 
   
print(df) 

     name  degree  score
0   Sunil     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98


In [110]:
# Import pandas package  
import pandas as pd 
   
# Define a dictionary containing Students data 
data = {'Height': [5.1, 6.2, 5.1, 5.2], 
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'Hobby': ['Poetry', 'Travelling', 'Biking', 'Sports']} 
 
df = pd.DataFrame(data)
df.index = ['Sarah', 'Princi', 'Gaurav', 'Anuj']
 
1
2
# select two rows
df.loc[["Sarah", "Princi"]]


Height Qualification       Hobby
Sarah      5.1           Msc      Poetry
Princi     6.2            MA  Travelling

In [116]:
# Import pandas package  
import pandas as pd 
   
# Define a dictionary containing Students data 
data = {'Height': [5.1, 6.2, 5.1, 5.2], 
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'Hobby': ['Poetry', 'Travelling', 'Biking', 'Sports']} 
 
df = pd.DataFrame(data)
df.index = ['Sarah', 'Princi', 'Gaurav', 'Anuj']
 
print(df)
 
 
new_row = pd.DataFrame({'Height': 5.3, 'Qualification': 'Bachelor' , 'Hobby': 'Sports'}, 
                                                            index =['NewRow'])
df = pd.concat([new_row, df])
 
print ('\n After adding row NewRow \n')
 
df

        Height Qualification       Hobby
Sarah      5.1           Msc      Poetry
Princi     6.2            MA  Travelling
Gaurav     5.1           Msc      Biking
Anuj       5.2           Msc      Sports

 After adding row NewRow 



Height Qualification       Hobby
NewRow     5.3      Bachelor      Sports
Sarah      5.1           Msc      Poetry
Princi     6.2            MA  Travelling
Gaurav     5.1           Msc      Biking
Anuj       5.2           Msc      Sports

In [139]:
# Import pandas package  
import pandas as pd 
   
# Define a dictionary containing Students data 
data = {'Name': ['Sarah', 'Princi', 'Gaurav'], 
        'Height': [5.1, 6.2, 5.1], 
        'Qualification': ['Msc', 'MA', 'Msc'],
        'Hobby': ['Poetry', 'Travelling', 'Biking']} 
   
# Convert the dictionary into DataFrame 
df = pd.DataFrame(data) 

# Define a dictionary containing New data to append
data = {'Name': ['Janvi', 'Rushel'], 
        'Height': [5.1, 6.2], 
        'Qualification': ['Msc', 'MA'],
        'Hobby': ['Poetry', 'Travelling']} 
   
# Convert the dictionary into DataFrame 
df_to_append = pd.DataFrame(data) 

#append the df_to_append to the original dataframe
df.append(df_to_append, ignore_index= True)
print(df_to_append)
print(df)


     Name  Height Qualification       Hobby
0   Janvi     5.1           Msc      Poetry
1  Rushel     6.2            MA  Travelling
     Name  Height Qualification       Hobby
0   Sarah     5.1           Msc      Poetry
1  Princi     6.2            MA  Travelling
2  Gaurav     5.1           Msc      Biking


In [154]:
# Import pandas package  
import pandas as pd 
   
# Define a dictionary containing Students data 
data = {'Name': ['Sarah', 'Princi', 'Gaurav'], 
        'Height': [5.1, 6.2, 5.1], 
        'Qualification': ['Msc', 'MA', 'Msc'],
        'Hobby': ['Poetry', 'Travelling', 'Biking']} 
   
# Convert the dictionary into DataFrame 
df = pd.DataFrame(data) 
 
print(df)
 
print('\n After dropping \n')
 
df.drop([0,1])

     Name  Height Qualification       Hobby
0   Sarah     5.1           Msc      Poetry
1  Princi     6.2            MA  Travelling
2  Gaurav     5.1           Msc      Biking

 After dropping 



Name  Height Qualification   Hobby
2  Gaurav     5.1           Msc  Biking

In [159]:
You can rename index names rename() function.

import pandas as pd 
   
# making data frame from csv file 
# Define a dictionary containing Students data 
data = {'Name': ['Sarah', 'Princi', 'Gaurav'], 
        'Height': [5.1, 6.2, 5.1], 
        'Qualification': ['Msc', 'MA', 'Msc'],
        'Hobby': ['Poetry', 'Travelling', 'Biking']} 
   
# Convert the dictionary into DataFrame 
df = pd.DataFrame(data) 

# changing index cols with rename() to 1st, 2nd &amp; 3rd Record respectively
df.rename(index = {  0: "1st Record", 
                     1:"2nd Record", 
                     2: "3rd Record"}, 
                                 inplace = True) 
# display 
df 

SyntaxError: invalid syntax (<ipython-input-159-4cc082f2300a>, line 1)

In [175]:

# Import pandas package
import pandas as pd
  
# Define a dictionary containing employee data
data = {'Name':['Sarah', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Kolkata', 'Kanpur', 'Allahabad', 'Delhi'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}
  
# Convert the dictionary into DataFrame 
df = pd.DataFrame(data)
 
 
# select all rows by ':' 
# select two columns Name and Qualification by their position
 
df[df.columns[0:3]] 

Name  Age    Address
0   Sarah   27    Kolkata
1  Princi   24     Kanpur
2  Gaurav   22  Allahabad
3    Anuj   32      Delhi

In [177]:
df = pd.read_csv("https://gist.githubusercontent.com/tiangechen/b68782efa49a16edaf07dc2cdaa855ea/raw/0c794a9717f18b094eabab2cd6a6b9a226903577/movies.csv")
df

Film    Genre            Lead Studio  \
0           Zack and Miri Make a Porno  Romance  The Weinstein Company   
1                      Youth in Revolt   Comedy  The Weinstein Company   
2   You Will Meet a Tall Dark Stranger   Comedy            Independent   
3                         When in Rome   Comedy                 Disney   
4                What Happens in Vegas   Comedy                    Fox   
..                                 ...      ...                    ...   
72                 Across the Universe  romance            Independent   
73                       A Serious Man    Drama              Universal   
74                  A Dangerous Method    Drama            Independent   
75                          27 Dresses   Comedy                    Fox   
76                (500) Days of Summer   comedy                    Fox   

    Audience score %  Profitability  Rotten Tomatoes % Worldwide Gross  Year  
0                 70       1.747542                 64         $41.94   2008  
1                 52       1.090000                 68         $19.62   2010  
2                 35       1.211818                 43         $26.66   2010  
3                 44       0.000000                 15         $43.04   2010  
4                 72       6.267647                 28        $219.37   2008  
..               ...            ...                ...             ...   ...  
72                84       0.652603                 54         $29.37   2007  
73                64       4.382857                 89         $30.68   2009  
74                89       0.448645                 79          $8.97   2011  
75                71       5.343622                 40        $160.31   2008  
76                81       8.096000                 87         $60.72   2009  

[77 rows x 8 columns]

In [303]:
# Import pandas package  
import pandas as pd 
   
# Define a dictionary containing Students data 
data = {'Height': [5.1, 6.2, 5.1, 5.2], 
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'Hobby': ['Poetry', 'Travelling', 'Biking', 'Sports']} 
 
df = pd.DataFrame(data)
df.index = ['Sarah', 'Princi', 'Gaurav', 'Anuj']
 
print(df)

print("\n After droping the last two rows")


df.drop(["Sarah", "Anuj"])


        Height Qualification       Hobby
Sarah      5.1           Msc      Poetry
Princi     6.2            MA  Travelling
Gaurav     5.1           Msc      Biking
Anuj       5.2           Msc      Sports

 After droping the last two rows


Height Qualification       Hobby
Princi     6.2            MA  Travelling
Gaurav     5.1           Msc      Biking

In [269]:
# Import pandas package  
import pandas as pd 
   
# Define a dictionary containing Students data 
data = {'Name': ['Sarah', 'Princi', 'Gaurav'], 
        'Height': [5.1, 6.2, 5.1], 
        'Qualification': ['Msc', 'MA', 'Msc'],
        'Hobby': ['Poetry', 'Travelling', 'Biking']} 
   
# Convert the dictionary into DataFrame 
df = pd.DataFrame(data) 
 
print(df)
 
print('\n After dropping \n')
 
df.drop([0])

     Name  Height Qualification       Hobby
0   Sarah     5.1           Msc      Poetry
1  Princi     6.2            MA  Travelling
2  Gaurav     5.1           Msc      Biking

 After dropping 



Name  Height Qualification       Hobby
1  Princi     6.2            MA  Travelling
2  Gaurav     5.1           Msc      Biking

In [305]:
import pandas as pd
df= pd.read_csv("movies.csv")

df[(df['Year'] == 2007) & (df['Genre'] == 'Comedy') & (df['Lead Studio'] == 'Warner Bros.')]

Film   Genre   Lead Studio  Audience score %  Profitability  \
36  No Reservations  Comedy  Warner Bros.                64       3.307180   
51   License to Wed  Comedy  Warner Bros.                55       1.980206   

    Rotten Tomatoes % Worldwide Gross  Year  
36                 39         $92.60   2007  
51                  8         $69.31   2007